# Generated by Django 3.0.8 on 2020-11-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentregisterform',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
